-- Seed: eight believable Cursor Roadshow Bangalore attendees
-- last_seen_at is set relative at runtime via worker bootstrap if needed;
-- these use fixed timestamps that the API treats as active when near "now".
-- For local demos, heartbeat/seed refresh keeps them present.

INSERT OR IGNORE INTO attendees (
  id, slug, name, x_handle, github_handle, avatar_url, project, looking_for,
  outfit_clue, venue_zone, open_to_meet, cursor_color, cursor_code,
  edit_token_hash, last_seen_at, created_at
) VALUES
(
  'seed_deepak',
  'deepak',
  'Deepak',
  'deepakbuilds',
  'deepak-infra',
  NULL,
  'Developer infrastructure for agent workflows',
  'People shipping autonomous coding agents',
  'Grey hoodie, red backpack',
  'Stage right',
  1,
  '#f54e00',
  'M4',
  'seed_hash_deepak',
  9999999999999,
  1754000000000
),
(
  'seed_ananya',
  'ananya',
  'Ananya',
  'ananya_codes',
  'ananya-r',
  NULL,
  'A design system that ships itself',
  'Collaborators for creative coding workshop projects',
  'Black shirt, silver laptop stickers',
  'Workshop',
  1,
  '#c0a8dd',
  'K7',
  'seed_hash_ananya',
  9999999999999,
  1754000001000
),
(
  'seed_rahul',
  'rahul',
  'Rahul',
  'rahuldotdev',
  'rahulsharma',
  NULL,
  'Local-first notes with agent memory',
  'Anyone building with agents who wants to jam',
  'Olive cap, white sneakers',
  'Coffee',
  1,
  '#9fbbe0',
  'R2',
  'seed_hash_rahul',
  9999999999999,
  1754000002000
),
(
  'seed_meera',
  'meera',
  'Meera',
  'meeraviz',
  'meera-v',
  NULL,
  'Realtime collab canvas for pair debugging',
  'Open to meet frontend + DX folks',
  'Mustard tote, wire-rim glasses',
  'Entrance',
  1,
  '#dfa88f',
  'V9',
  'seed_hash_meera',
  9999999999999,
  1754000003000
),
(
  'seed_arjun',
  'arjun',
  'Arjun',
  'arjun_ship',
  'arjunp',
  NULL,
  'CI that reviews PRs before humans wake up',
  'Looking for collaborators on eval harnesses',
  'Navy blazer, no bag',
  'Stage left',
  1,
  '#9fc9a2',
  'A1',
  'seed_hash_arjun',
  9999999999999,
  1754000004000
),
(
  'seed_priya',
  'priya',
  'Priya',
  'priya_loops',
  'priya-n',
  NULL,
  'Voice-to-PR for mobile developers',
  'Builders exploring Cursor workflows',
  'Floral scarf, black jeans',
  'Food',
  1,
  '#c08532',
  'P3',
  'seed_hash_priya',
  9999999999999,
  1754000005000
),
(
  'seed_vikram',
  'vikram',
  'Vikram',
  'vikramhq',
  'vikramk',
  NULL,
  'A tiny agent that finds you IRL meetups',
  'People open to meeting about event tooling',
  'Blue denim jacket, headphones around neck',
  'Outside',
  1,
  '#267f99',
  'X8',
  'seed_hash_vikram',
  9999999999999,
  1754000006000
),
(
  'seed_sara',
  'sara',
  'Sara',
  'sara_makes',
  'saramakes',
  NULL,
  'Creative coding sketches that become product UI',
  'Workshop table neighbors and agent builders',
  'Striped tee, camera bag',
  'Workshop',
  1,
  '#cf2d56',
  'S5',
  'seed_hash_sara',
  9999999999999,
  1754000007000
);
